"""Created db

Revision ID: 62abdfd4cca9
Revises: 
Create Date: 2023-12-10 14:01:50.329569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62abdfd4cca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('albumdetails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('albumid', sa.Integer(), nullable=False),
    sa.Column('songid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creatoralbum',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('album_name', sa.Integer(), nullable=False),
    sa.Column('albumratings', sa.Integer(), nullable=True),
    sa.Column('albumratingcount', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genrename', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genrename')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('songid', sa.Integer(), nullable=False),
    sa.Column('ratedby', sa.String(), nullable=False),
    sa.Column('ratingvalue', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('songname', sa.String(length=100), nullable=False),
    sa.Column('releasedate', sa.Date(), nullable=True),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('singer', sa.String(length=100), nullable=True),
    sa.Column('uploadedby', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('averagerating', sa.Integer(), nullable=True),
    sa.Column('ratingcount', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('songname')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('usertype', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('useralbum',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('album_name', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useralbumdetails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('albumid', sa.Integer(), nullable=False),
    sa.Column('songid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useralbumdetails')
    op.drop_table('useralbum')
    op.drop_table('user')
    op.drop_table('songs')
    op.drop_table('ratings')
    op.drop_table('genres')
    op.drop_table('creatoralbum')
    op.drop_table('albumdetails')
    op.drop_table('admin')
    # ### end Alembic commands ###
